spring:
  application:
    name: blog-app
  security:
    user:
      name: elijah
      password: love

  datasource:
    password: ${DB_PASSWORD1}
    url: ${DB_URL1}
    username: ${DB_USERNAME1}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: ${PORT}

jwt:
  secret: ${JWT}
  refresh-secret: ${REFRESH_TOKEN}
