spring:
  application:
    name: blog-app


  datasource:
    password: ${DB_PASSWORD1}
    url: ${DB_URL1}
    username: ${DB_USERNAME1}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        use_sql_comments: true
        highlight_sql: true
        generate_statistics: true

        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8088

jwt:
  secret: ${JWT}
  refresh-secret: ${REFRESH_TOKEN}

frontend:
  url: ${FRONTEND}
