spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8088/login/oauth2/code/google
            scope:
              - openid
              - profile
              - email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: http://localhost:8088/login/oauth2/code/github
            scope:
              - read:user
              - user:email
        provider:
          google:
            issuer-uri: https://accounts.google.com
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}



  application:
    name: blog-app


  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    driver-class-name: ${DB_DRIVER}
    hikari:
      max-lifetime: 1800000      # 30 minutes (safe default)
      idle-timeout: 600000       # 10 minutes
      keepalive-time: 300000     # 5 minutes - keeps connections alive
      minimum-idle: 5
      maximum-pool-size: 10


  cache:
    type: caffeine
    cache-names:
      - posts
      - userTotal
      - postById
      - postByTitle
      - users
      - myPostReaction
      - postsByCategory
      - postReactions
      - userById
      - userByEmail
      - userBlogHistory
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m   # Cache size + expiration time

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          jdbc:
            lob.non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8088

jwt:
  secret: ${JWT}
  refresh-secret: ${REFRESH_TOKEN}

frontend:
  url: ${FRONTEND}

cookie:
  domain: localhost
  secure: false

app:
  admin:
    name: ${ADMIN_NAME}
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}


logging:
  level:
    org.springframework.web.client.RestClient: DEBUG
    org.springframework.web.client.DefaultRestClient: DEBUG
    org.springframework.ai.openai.api: DEBUG
    org.springframework.security: INFO
    org.springframework.cache: DEBUG
